[package]
name = "rust_securerom_payload"
version = "0.1.0"
edition = "2018"
panic = "abort"

[lib]
crate-type = ["staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
