name: gala CI

on:
  [
    push,
    pull_request,
    # Allows running the workflow manually from the Actions tab
    workflow_dispatch
  ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out repo at $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: "Install system dependencies"
        run: |
          sudo apt-get install -y irecovery openssl rustc libusb-dev libirecovery-1.0-3
      - name: "Install Python dependencies"
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Linting
        shell: bash
        run: |
          invoke autoformat-lint

      - name: Build gala toolchain
        shell: bash
        run: |
          invoke setup-toolchain
